"""initial_schema_multi_tenant_with_global_sensitive_fields

Revision ID: e1dd99f6c0b2
Revises: 
Create Date: 2025-11-20 23:30:47.084067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1dd99f6c0b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('akm_projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_akm_projects_id'), 'akm_projects', ['id'], unique=False)
    op.create_index(op.f('ix_akm_projects_is_active'), 'akm_projects', ['is_active'], unique=False)
    op.create_index(op.f('ix_akm_projects_prefix'), 'akm_projects', ['prefix'], unique=True)
    op.create_table('akm_webhook_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('payload_schema', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_akm_webhook_events_event_type'), 'akm_webhook_events', ['event_type'], unique=True)
    op.create_index(op.f('ix_akm_webhook_events_id'), 'akm_webhook_events', ['id'], unique=False)
    op.create_table('akm_api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['akm_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_akm_key_hash_active', 'akm_api_keys', ['key_hash', 'is_active'], unique=False)
    op.create_index('idx_akm_key_project', 'akm_api_keys', ['project_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_akm_api_keys_id'), 'akm_api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_akm_api_keys_is_active'), 'akm_api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_akm_api_keys_key_hash'), 'akm_api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_akm_api_keys_project_id'), 'akm_api_keys', ['project_id'], unique=False)
    op.create_table('akm_scopes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('scope_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['akm_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'scope_name', name='uq_project_scope')
    )
    op.create_index('idx_scopes_project_active', 'akm_scopes', ['project_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_akm_scopes_id'), 'akm_scopes', ['id'], unique=False)
    op.create_index(op.f('ix_akm_scopes_project_id'), 'akm_scopes', ['project_id'], unique=False)
    op.create_table('akm_sensitive_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('strategy', sa.String(length=20), nullable=True),
    sa.Column('mask_show_start', sa.Integer(), nullable=True),
    sa.Column('mask_show_end', sa.Integer(), nullable=True),
    sa.Column('mask_char', sa.String(length=1), nullable=True),
    sa.Column('replacement', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['akm_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'field_name', name='uq_project_sensitive_field')
    )
    op.create_index('idx_sensitive_field_active', 'akm_sensitive_fields', ['is_active'], unique=False)
    op.create_index('idx_sensitive_field_project', 'akm_sensitive_fields', ['project_id', 'field_name'], unique=False)
    op.create_index(op.f('ix_akm_sensitive_fields_field_name'), 'akm_sensitive_fields', ['field_name'], unique=False)
    op.create_index(op.f('ix_akm_sensitive_fields_id'), 'akm_sensitive_fields', ['id'], unique=False)
    op.create_index(op.f('ix_akm_sensitive_fields_is_active'), 'akm_sensitive_fields', ['is_active'], unique=False)
    op.create_index(op.f('ix_akm_sensitive_fields_project_id'), 'akm_sensitive_fields', ['project_id'], unique=False)
    op.create_table('akm_alert_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('threshold_value', sa.Integer(), nullable=False),
    sa.Column('threshold_percentage', sa.Integer(), nullable=True),
    sa.Column('comparison_operator', sa.String(length=10), nullable=False),
    sa.Column('window_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['akm_api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_akm_alert_key', 'akm_alert_rules', ['api_key_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_akm_alert_rules_api_key_id'), 'akm_alert_rules', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_akm_alert_rules_id'), 'akm_alert_rules', ['id'], unique=False)
    op.create_table('akm_api_key_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('rate_limit_enabled', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_requests', sa.Integer(), nullable=True),
    sa.Column('rate_limit_window_seconds', sa.Integer(), nullable=True),
    sa.Column('daily_request_limit', sa.Integer(), nullable=True),
    sa.Column('monthly_request_limit', sa.Integer(), nullable=True),
    sa.Column('ip_whitelist_enabled', sa.Boolean(), nullable=False),
    sa.Column('allowed_ips', sa.JSON(), nullable=True),
    sa.Column('allowed_time_start', sa.Time(), nullable=True),
    sa.Column('allowed_time_end', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['akm_api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_akm_api_key_configs_api_key_id'), 'akm_api_key_configs', ['api_key_id'], unique=True)
    op.create_index(op.f('ix_akm_api_key_configs_id'), 'akm_api_key_configs', ['id'], unique=False)
    op.create_table('akm_api_key_scopes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['akm_api_keys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scope_id'], ['akm_scopes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_id', 'scope_id', name='uq_api_key_scope')
    )
    op.create_index('idx_akm_key_scope', 'akm_api_key_scopes', ['api_key_id', 'scope_id'], unique=False)
    op.create_index(op.f('ix_akm_api_key_scopes_id'), 'akm_api_key_scopes', ['id'], unique=False)
    op.create_table('akm_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('http_method', sa.String(length=10), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['akm_api_keys.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['akm_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_correlation', 'akm_audit_logs', ['correlation_id'], unique=False)
    op.create_index('idx_audit_hash', 'akm_audit_logs', ['entry_hash'], unique=False)
    op.create_index('idx_audit_key_time', 'akm_audit_logs', ['api_key_id', sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_audit_operation', 'akm_audit_logs', ['operation', sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_audit_project_time', 'akm_audit_logs', ['project_id', sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_audit_resource', 'akm_audit_logs', ['resource_type', 'resource_id', sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_audit_status', 'akm_audit_logs', ['status', sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_audit_timestamp', 'akm_audit_logs', [sa.text('timestamp DESC')], unique=False)
    op.create_index(op.f('ix_akm_audit_logs_action'), 'akm_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_akm_audit_logs_api_key_id'), 'akm_audit_logs', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_akm_audit_logs_correlation_id'), 'akm_audit_logs', ['correlation_id'], unique=True)
    op.create_index(op.f('ix_akm_audit_logs_entry_hash'), 'akm_audit_logs', ['entry_hash'], unique=False)
    op.create_index(op.f('ix_akm_audit_logs_id'), 'akm_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_akm_audit_logs_ip_address'), 'akm_audit_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_akm_audit_logs_operation'), 'akm_audit_logs', ['operation'], unique=False)
    op.create_index(op.f('ix_akm_audit_logs_project_id'), 'akm_audit_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_akm_audit_logs_resource_type'), 'akm_audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_akm_audit_logs_response_status'), 'akm_audit_logs', ['response_status'], unique=False)
    op.create_index(op.f('ix_akm_audit_logs_status'), 'akm_audit_logs', ['status'], unique=False)
    op.create_index(op.f('ix_akm_audit_logs_timestamp'), 'akm_audit_logs', ['timestamp'], unique=False)
    op.create_table('akm_rate_limit_buckets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['akm_api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_id', 'window_start', name='uq_rate_bucket')
    )
    op.create_index('idx_akm_rate_bucket_window', 'akm_rate_limit_buckets', ['api_key_id', 'window_start', 'window_end'], unique=False)
    op.create_index(op.f('ix_akm_rate_limit_buckets_id'), 'akm_rate_limit_buckets', ['id'], unique=False)
    op.create_table('akm_usage_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('successful_requests', sa.Integer(), nullable=False),
    sa.Column('failed_requests', sa.Integer(), nullable=False),
    sa.Column('avg_response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['akm_api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_id', 'date', 'hour', name='uq_usage_metric')
    )
    op.create_index('idx_akm_usage_key_date', 'akm_usage_metrics', ['api_key_id', 'date'], unique=False)
    op.create_index(op.f('ix_akm_usage_metrics_id'), 'akm_usage_metrics', ['id'], unique=False)
    op.create_table('akm_webhooks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('retry_policy', sa.JSON(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['akm_api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_akm_webhooks_api_key_id'), 'akm_webhooks', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_akm_webhooks_id'), 'akm_webhooks', ['id'], unique=False)
    op.create_table('akm_webhook_deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('webhook_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['webhook_id'], ['akm_webhooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_akm_delivery_retry', 'akm_webhook_deliveries', ['status', 'next_retry_at'], unique=False)
    op.create_index('idx_akm_delivery_webhook', 'akm_webhook_deliveries', ['webhook_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_akm_webhook_deliveries_id'), 'akm_webhook_deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_akm_webhook_deliveries_status'), 'akm_webhook_deliveries', ['status'], unique=False)
    op.create_table('akm_webhook_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('webhook_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_type'], ['akm_webhook_events.event_type'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['webhook_id'], ['akm_webhooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('webhook_id', 'event_type', name='uq_webhook_event')
    )
    op.create_index('idx_akm_webhook_sub', 'akm_webhook_subscriptions', ['webhook_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_akm_webhook_subscriptions_id'), 'akm_webhook_subscriptions', ['id'], unique=False)
    op.create_table('akm_alert_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_rule_id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('metric_value', sa.Integer(), nullable=False),
    sa.Column('threshold_value', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('webhook_delivery_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['akm_alert_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['webhook_delivery_id'], ['akm_webhook_deliveries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_akm_alert_hist_rule', 'akm_alert_history', ['alert_rule_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_akm_alert_history_api_key_id'), 'akm_alert_history', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_akm_alert_history_id'), 'akm_alert_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_akm_alert_history_id'), table_name='akm_alert_history')
    op.drop_index(op.f('ix_akm_alert_history_api_key_id'), table_name='akm_alert_history')
    op.drop_index('idx_akm_alert_hist_rule', table_name='akm_alert_history')
    op.drop_table('akm_alert_history')
    op.drop_index(op.f('ix_akm_webhook_subscriptions_id'), table_name='akm_webhook_subscriptions')
    op.drop_index('idx_akm_webhook_sub', table_name='akm_webhook_subscriptions')
    op.drop_table('akm_webhook_subscriptions')
    op.drop_index(op.f('ix_akm_webhook_deliveries_status'), table_name='akm_webhook_deliveries')
    op.drop_index(op.f('ix_akm_webhook_deliveries_id'), table_name='akm_webhook_deliveries')
    op.drop_index('idx_akm_delivery_webhook', table_name='akm_webhook_deliveries')
    op.drop_index('idx_akm_delivery_retry', table_name='akm_webhook_deliveries')
    op.drop_table('akm_webhook_deliveries')
    op.drop_index(op.f('ix_akm_webhooks_id'), table_name='akm_webhooks')
    op.drop_index(op.f('ix_akm_webhooks_api_key_id'), table_name='akm_webhooks')
    op.drop_table('akm_webhooks')
    op.drop_index(op.f('ix_akm_usage_metrics_id'), table_name='akm_usage_metrics')
    op.drop_index('idx_akm_usage_key_date', table_name='akm_usage_metrics')
    op.drop_table('akm_usage_metrics')
    op.drop_index(op.f('ix_akm_rate_limit_buckets_id'), table_name='akm_rate_limit_buckets')
    op.drop_index('idx_akm_rate_bucket_window', table_name='akm_rate_limit_buckets')
    op.drop_table('akm_rate_limit_buckets')
    op.drop_index(op.f('ix_akm_audit_logs_timestamp'), table_name='akm_audit_logs')
    op.drop_index(op.f('ix_akm_audit_logs_status'), table_name='akm_audit_logs')
    op.drop_index(op.f('ix_akm_audit_logs_response_status'), table_name='akm_audit_logs')
    op.drop_index(op.f('ix_akm_audit_logs_resource_type'), table_name='akm_audit_logs')
    op.drop_index(op.f('ix_akm_audit_logs_project_id'), table_name='akm_audit_logs')
    op.drop_index(op.f('ix_akm_audit_logs_operation'), table_name='akm_audit_logs')
    op.drop_index(op.f('ix_akm_audit_logs_ip_address'), table_name='akm_audit_logs')
    op.drop_index(op.f('ix_akm_audit_logs_id'), table_name='akm_audit_logs')
    op.drop_index(op.f('ix_akm_audit_logs_entry_hash'), table_name='akm_audit_logs')
    op.drop_index(op.f('ix_akm_audit_logs_correlation_id'), table_name='akm_audit_logs')
    op.drop_index(op.f('ix_akm_audit_logs_api_key_id'), table_name='akm_audit_logs')
    op.drop_index(op.f('ix_akm_audit_logs_action'), table_name='akm_audit_logs')
    op.drop_index('idx_audit_timestamp', table_name='akm_audit_logs')
    op.drop_index('idx_audit_status', table_name='akm_audit_logs')
    op.drop_index('idx_audit_resource', table_name='akm_audit_logs')
    op.drop_index('idx_audit_project_time', table_name='akm_audit_logs')
    op.drop_index('idx_audit_operation', table_name='akm_audit_logs')
    op.drop_index('idx_audit_key_time', table_name='akm_audit_logs')
    op.drop_index('idx_audit_hash', table_name='akm_audit_logs')
    op.drop_index('idx_audit_correlation', table_name='akm_audit_logs')
    op.drop_table('akm_audit_logs')
    op.drop_index(op.f('ix_akm_api_key_scopes_id'), table_name='akm_api_key_scopes')
    op.drop_index('idx_akm_key_scope', table_name='akm_api_key_scopes')
    op.drop_table('akm_api_key_scopes')
    op.drop_index(op.f('ix_akm_api_key_configs_id'), table_name='akm_api_key_configs')
    op.drop_index(op.f('ix_akm_api_key_configs_api_key_id'), table_name='akm_api_key_configs')
    op.drop_table('akm_api_key_configs')
    op.drop_index(op.f('ix_akm_alert_rules_id'), table_name='akm_alert_rules')
    op.drop_index(op.f('ix_akm_alert_rules_api_key_id'), table_name='akm_alert_rules')
    op.drop_index('idx_akm_alert_key', table_name='akm_alert_rules')
    op.drop_table('akm_alert_rules')
    op.drop_index(op.f('ix_akm_sensitive_fields_project_id'), table_name='akm_sensitive_fields')
    op.drop_index(op.f('ix_akm_sensitive_fields_is_active'), table_name='akm_sensitive_fields')
    op.drop_index(op.f('ix_akm_sensitive_fields_id'), table_name='akm_sensitive_fields')
    op.drop_index(op.f('ix_akm_sensitive_fields_field_name'), table_name='akm_sensitive_fields')
    op.drop_index('idx_sensitive_field_project', table_name='akm_sensitive_fields')
    op.drop_index('idx_sensitive_field_active', table_name='akm_sensitive_fields')
    op.drop_table('akm_sensitive_fields')
    op.drop_index(op.f('ix_akm_scopes_project_id'), table_name='akm_scopes')
    op.drop_index(op.f('ix_akm_scopes_id'), table_name='akm_scopes')
    op.drop_index('idx_scopes_project_active', table_name='akm_scopes')
    op.drop_table('akm_scopes')
    op.drop_index(op.f('ix_akm_api_keys_project_id'), table_name='akm_api_keys')
    op.drop_index(op.f('ix_akm_api_keys_key_hash'), table_name='akm_api_keys')
    op.drop_index(op.f('ix_akm_api_keys_is_active'), table_name='akm_api_keys')
    op.drop_index(op.f('ix_akm_api_keys_id'), table_name='akm_api_keys')
    op.drop_index('idx_akm_key_project', table_name='akm_api_keys')
    op.drop_index('idx_akm_key_hash_active', table_name='akm_api_keys')
    op.drop_table('akm_api_keys')
    op.drop_index(op.f('ix_akm_webhook_events_id'), table_name='akm_webhook_events')
    op.drop_index(op.f('ix_akm_webhook_events_event_type'), table_name='akm_webhook_events')
    op.drop_table('akm_webhook_events')
    op.drop_index(op.f('ix_akm_projects_prefix'), table_name='akm_projects')
    op.drop_index(op.f('ix_akm_projects_is_active'), table_name='akm_projects')
    op.drop_index(op.f('ix_akm_projects_id'), table_name='akm_projects')
    op.drop_table('akm_projects')
    # ### end Alembic commands ###
